"""Serves the shared scam-detection pattern bundle.

The same `patterns.json` that the Python backend uses is exposed here so the
Android app (hello-hari) can fetch fresh patterns over-the-air and fall back
to its bundled asset when offline.

Generated by: scripts/export_patterns_json.py
"""

from __future__ import annotations

import hashlib
import json
import logging
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request, Response
from fastapi.responses import JSONResponse

_logger = logging.getLogger(__name__)

router = APIRouter(tags=["patterns"])

_PATTERNS_FILE = Path(__file__).resolve().parent.parent / "detection" / "patterns.json"

# Read once at import time — patterns are static per deployment.
_cached_bytes: bytes | None = None
_cached_etag: str | None = None
_cached_meta: dict | None = None


def _load() -> tuple[bytes, str, dict]:
    global _cached_bytes, _cached_etag, _cached_meta
    if _cached_bytes is not None and _cached_etag is not None and _cached_meta is not None:
        return _cached_bytes, _cached_etag, _cached_meta

    if not _PATTERNS_FILE.is_file():
        raise HTTPException(
            status_code=503,
            detail=(
                "patterns.json not found. Run `python scripts/export_patterns_json.py` "
                "to generate it from the Python source of truth."
            ),
        )

    raw = _PATTERNS_FILE.read_bytes()
    etag = hashlib.sha256(raw).hexdigest()[:16]
    data = json.loads(raw)
    meta = {
        "schema_version": data.get("schema_version"),
        "generated_at": data.get("generated_at"),
        "stats": data.get("stats", {}),
        "etag": etag,
    }

    _cached_bytes = raw
    _cached_etag = etag
    _cached_meta = meta
    _logger.info(
        "Loaded patterns.json etag=%s categories=%s phrases=%s archetypes=%s",
        etag,
        meta["stats"].get("pattern_categories_count"),
        meta["stats"].get("total_exact_phrases"),
        meta["stats"].get("archetypes_count"),
    )
    return raw, etag, meta


@router.get("/patterns.json")
async def get_patterns(request: Request) -> Response:
    """Full pattern bundle. Honors If-None-Match for cheap OTA polling."""
    raw, etag, _ = _load()
    quoted = f'"{etag}"'
    if request.headers.get("if-none-match") == quoted:
        return Response(status_code=304, headers={"ETag": quoted})
    return Response(
        content=raw,
        media_type="application/json",
        headers={
            "ETag": quoted,
            # 5-minute browser/app cache; clients should still revalidate via ETag.
            "Cache-Control": "public, max-age=300, must-revalidate",
        },
    )


@router.get("/patterns/meta")
async def get_patterns_meta() -> JSONResponse:
    """Lightweight metadata endpoint — lets clients check for updates without
    downloading the full bundle."""
    _, _, meta = _load()
    return JSONResponse(meta)
